apiVersion: v1
kind: Service
metadata:
  labels:
    app: account-service
    project: piggymetrics
    tier: backend
  name: account-service
  namespace: default
spec:
  ports:
  - name: http
    port: 6000
    protocol: TCP
    targetPort: 6000
  selector:
    app: account-service
    project: piggymetrics
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
