apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-mongodb
    project: piggymetrics
    tier: database
  name: auth-mongodb
  namespace: default
spec:
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: auth-mongodb
    project: piggymetrics
    tier: database
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
