apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-service
    project: piggymetrics
    tier: infrastructure
  name: auth-service
  namespace: default
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: auth-service
    project: piggymetrics
    tier: infrastructure
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
