apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
    project: piggymetrics
    tier: frontend
  name: gateway
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 4000
  selector:
    app: gateway
    project: piggymetrics
    tier: frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
