apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitoring
    project: piggymetrics
    tier: infrastructure
  name: monitoring
  namespace: default
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 8080
  selector:
    app: monitoring
    project: piggymetrics
    tier: infrastructure
  sessionAffinity: None
  type: ClusterIP

