apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-service
    project: piggymetrics
    tier: backend
  name: notification-service
  namespace: default
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: notification-service
    project: piggymetrics
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
