apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
    project: piggymetrics
    tier: infrastructure
  name: rabbitmq
  namespace: default
spec:
  ports:
  - name: http
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: rabbitmq
    project: piggymetrics
    tier: infrastructure
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
