apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
    project: piggymetrics
    tier: infrastructure
  name: registry
  namespace: default
spec:
  ports:
  - name: http
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: registry
    project: piggymetrics
    tier: infrastructure
  type: ClusterIP
status:
  loadBalancer: {}

