apiVersion: v1
kind: Service
metadata:
  labels:
    app: statistics-service
    project: piggymetrics
    tier: backend
  name: statistics-service
  namespace: default
spec:
  ports:
  - name: http
    port: 7000
    protocol: TCP
    targetPort: 7000
  selector:
    app: statistics-service
    project: piggymetrics
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
