apiVersion: v1
kind: Service
metadata:
  labels:
    app: turbine-stream-service
    project: piggymetrics
    tier: infrastructure
  name: turbine-stream-service
  namespace: default
spec:
  ports:
  - name: exposed
    port: 8989
    protocol: TCP
    targetPort: 8989
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: turbine-stream-service
    project: piggymetrics
    tier: infrastructure
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
