apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: account-service
    project: piggymetrics
    tier: backend
  name: account-service
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: account-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: account-service
        project: piggymetrics
        tier: backend
    spec:
      containers:
      - env:
        - name: ACCOUNT_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: account_service_password
              name: piggymetrics
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: config_service_password
              name: piggymetrics
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: account_mongodb_password
              name: piggymetrics
        image: cr-cn-beijing.volces.com/cloudnative/account-service:1.0
        imagePullPolicy: Always
        name: account-service
        ports:
        - containerPort: 6000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
