apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-service
    project: piggymetrics
    tier: infrastructure
  name: auth-service
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: auth-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-service
        project: piggymetrics
        tier: infrastructure
    spec:
      containers:
      - env:
        - name: ACCOUNT_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: account_service_password
              name: piggymetrics
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: config_service_password
              name: piggymetrics
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: auth_mongodb_password
              name: piggymetrics
        - name: NOTIFICATION_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: notification_service_password
              name: piggymetrics
        - name: STATISTICS_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: statistics_service_password
              name: piggymetrics
        image: cr-cn-beijing.volces.com/cloudnative/auth-service:1.0
        imagePullPolicy: Always
        name: auth-service
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

