apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-mongodb
    project: piggymetrics
    tier: database
  name: auth-mongodb
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: auth-mongodb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-mongodb
        project: piggymetrics
        tier: database
    spec:
      containers:
      - env:
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: auth_mongodb_password
              name: piggymetrics
        image: cr-cn-beijing.volces.com/cloudnative/mongodb:1.0
        imagePullPolicy: Always
        name: auth-mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

