apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: config
    project: piggymetrics
    tier: infrastructure
  labels:
    app: config
    project: piggymetrics
    tier: infrastructure
  name: config
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: config
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: config
        project: piggymetrics
        tier: infrastructure
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: config_service_password
              name: piggymetrics
        image: cr-cn-beijing.volces.com/cloudnative/config:1.0
        imagePullPolicy: Always
        name: config
        ports:
        - containerPort: 8888
          protocol: TCP
        resources:
          requests:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10

