apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-service
    project: piggymetrics
    tier: backend
  name: notification-service
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: notification-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: notification-service
        project: piggymetrics
        tier: backend
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: config_service_password
              name: piggymetrics
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: notification_mongodb_password
              name: piggymetrics
        - name: NOTIFICATION_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: notification_service_password
              name: piggymetrics
        - name: NOTIFICATION_EMAIL_HOST
          valueFrom:
            secretKeyRef:
              key: notification_email_host
              name: piggymetrics
        - name: NOTIFICATION_EMAIL_PORT
          valueFrom:
            secretKeyRef:
              key: notification_email_pass
              name: piggymetrics
        - name: NOTIFICATION_EMAIL_USER
          valueFrom:
            secretKeyRef:
              key: notification_email_user
              name: piggymetrics
        - name: NOTIFICATION_EMAIL_PASS
          valueFrom:
            secretKeyRef:
              key: notification_email_port
              name: piggymetrics
        image: cr-cn-beijing.volces.com/cloudnative/notification-service:1.0
        imagePullPolicy: Always
        name: notification-service
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
