apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registry
    project: piggymetrics
    tier: infrastructure
  name: registry
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: registry
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: registry
        project: piggymetrics
        tier: infrastructure
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: config_service_password
              name: piggymetrics
        image: cr-cn-beijing.volces.com/cloudnative/registry:1.0
        imagePullPolicy: Always
        name: registry
        ports:
        - containerPort: 8761
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

