apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: turbine-stream-service
    project: piggymetrics
    tier: infrastructure
  name: turbine-stream-service
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: turbine-stream-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: turbine-stream-service
        project: piggymetrics
        tier: infrastructure
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: config_service_password
              name: piggymetrics
        image: cr-cn-beijing.volces.com/cloudnative/turbine-stream-service:1.0
        imagePullPolicy: Always
        name: turbine-stream-service
        ports:
        - containerPort: 8989
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

